server-test/config/routes.rb
SnaTest::Application.routes.draw do
  resources :messages

  resources :person_relations

  resources :people

  match 'api/data/' => 'api#get_data', :via => :get

  match 'api/profile/' => 'api#register_profile', :via => :post
  
  match 'api/profile/' => 'api#update_profile', :via => :get

  match 'api/persons/*person_email/request-friendship/' => 'api#request_friendship', :via => :post

  match 'api/persons/*person_email/reject-friendship/' => 'api#reject_friendship', :via => :post

  match 'api/messages/*person_email/send-message/' => 'api#send_message', :via => :post

  match 'api/messages/:message_id/mark-as-read/' => 'api#mark_message_read', :via => :put

  match 'people/:id/friends' => 'people#friends', :as => :person_friends

  match 'people/:id/relations/:id2/remove' => 'people#remove_relation', :as => :remove_relation

  match 'people/:id/relations/:id2/add_friend' => 'people#add_friend', :as => :add_friend

  match 'people/:id/relations/:id2/add_waiting_for_him' => 'people#add_waiting_for_him', :as => :add_waiting_for_him

  match 'people/:id/relations/:id2/add_waiting_for_me' => 'people#add_waiting_for_me', :as => :add_waiting_for_me

  match 'people/:id/relations/:id2/add_rejected' => 'people#add_rejected', :as => :add_rejected
  

end

server-test/app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :from, :class_name => 'Person'
  belongs_to :to, :class_name => 'Person'
end

server-test/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # GET /messages
  # GET /messages.xml
  def index
    @messages = Message.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @messages }
    end
  end

  # GET /messages/1
  # GET /messages/1.xml
  def show
    @message = Message.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/new
  # GET /messages/new.xml
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.xml
  def create
    @message = Message.new(params[:message])

    respond_to do |format|
      if @message.save
        format.html { redirect_to(@message, :notice => 'Message was successfully created.') }
        format.xml  { render :xml => @message, :status => :created, :location => @message }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.xml
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to(@message, :notice => 'Message was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @message.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.xml
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to(messages_url) }
      format.xml  { head :ok }
    end
  end
end

server-test/app/helpers/messages_helper.rb
module MessagesHelper
end

server-test/app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <b>Id:</b>
    <%= @message.id %>
  </p>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :from_id %><br />
    <%= select 'message', 'from_id', Person.all.collect{|p| [p.email, p.id]}%>
  </div>
  <div class="field">
    <%= f.label :to_id %><br />
    <%= select 'message', 'to_id', Person.all.collect{|p| [p.email, p.id]}%>
  </div>
  <div class="field">
    <%= f.label :sent_on %><br />
    <%= f.text_field :sent_on, :class => 'datetime-picker'%>
  </div>
  <div class="field">
    <%= f.label :read_on %><br />
    <%= f.text_field :read_on, :class => 'datetime-picker'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server-test/app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

server-test/app/views/messages/index.html.erb
<h1>Listing messages</h1>

<table>
  <tr>
    <th>Id</th>
    <th>From</th>
    <th>To</th>
    <th>Text</th>
    <th>Sent on</th>
    <th>Read on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.id %></td>
    <td><%= message.from.email %></td>
    <td><%= message.to.email %></td>
    <td><%= message.text %></td>
    <td><%= message.sent_on %></td>
    <td><%= message.read_on %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

server-test/app/views/messages/new.html.erb
<h1>New message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

server-test/app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @message.id %>
</p>
<p>
  <b>From:</b>
  <%= @message.from.email %>
</p>

<p>
  <b>To:</b>
  <%= @message.to.email %>
</p>

<p>
  <b>Text:</b>
  <%= @message.text %>
</p>

<p>
  <b>Sent on:</b>
  <%= @message.sent_on %>
</p>

<p>
  <b>Read on:</b>
  <%= @message.read_on %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>