server-test/config/routes.rb
SnaTest::Application.routes.draw do
  resources :messages

  resources :person_relations

  resources :people

  match 'api/data/' => 'api#get_data', :via => :get

  match 'api/profile/' => 'api#register_profile', :via => :post
  
  match 'api/profile/' => 'api#update_profile', :via => :get

  match 'api/persons/*person_email/request-friendship/' => 'api#request_friendship', :via => :post

  match 'api/persons/*person_email/reject-friendship/' => 'api#reject_friendship', :via => :post

  match 'api/messages/*person_email/send-message/' => 'api#send_message', :via => :post

  match 'api/messages/:message_id/mark-as-read/' => 'api#mark_message_read', :via => :put

  match 'people/:id/friends' => 'people#friends', :as => :person_friends

  match 'people/:id/relations/:id2/remove' => 'people#remove_relation', :as => :remove_relation

  match 'people/:id/relations/:id2/add_friend' => 'people#add_friend', :as => :add_friend

  match 'people/:id/relations/:id2/add_waiting_for_him' => 'people#add_waiting_for_him', :as => :add_waiting_for_him

  match 'people/:id/relations/:id2/add_waiting_for_me' => 'people#add_waiting_for_me', :as => :add_waiting_for_me

  match 'people/:id/relations/:id2/add_rejected' => 'people#add_rejected', :as => :add_rejected
  

end

server-test/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>SnaTest</title>
  
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'ui-lightness/jquery-ui-1.8.14.custom' %>
  <%= stylesheet_link_tag 'custom' %>

  <%= javascript_include_tag 'prototype', 'jquery-1.6.2.min', 'jquery-ui-1.8.14.custom.min', 'jquery-ui-timepicker-addon', 'date.format', :defaults %>
  
  <%= csrf_meta_tag %>
  
</head>
<body>

<%= yield %>

  <br></br>
  
  <%= link_to 'Persons', people_path %> |
  <%= link_to 'Person relations', person_relations_path %> |
  <%= link_to 'Messages', messages_path %>

  <br></br>
  Current time: <%= DateTime.now.utc %>
</body>
</html>