server-test/config/routes.rb
SnaTest::Application.routes.draw do
  resources :messages

  resources :person_relations

  resources :people

  match 'api/data/' => 'api#get_data', :via => :get

  match 'api/profile/' => 'api#register_profile', :via => :post
  
  match 'api/profile/' => 'api#update_profile', :via => :get

  match 'api/persons/*person_email/request-friendship/' => 'api#request_friendship', :via => :post

  match 'api/persons/*person_email/reject-friendship/' => 'api#reject_friendship', :via => :post

  match 'api/messages/*person_email/send-message/' => 'api#send_message', :via => :post

  match 'api/messages/:message_id/mark-as-read/' => 'api#mark_message_read', :via => :put

  match 'people/:id/friends' => 'people#friends', :as => :person_friends

  match 'people/:id/relations/:id2/remove' => 'people#remove_relation', :as => :remove_relation

  match 'people/:id/relations/:id2/add_friend' => 'people#add_friend', :as => :add_friend

  match 'people/:id/relations/:id2/add_waiting_for_him' => 'people#add_waiting_for_him', :as => :add_waiting_for_him

  match 'people/:id/relations/:id2/add_waiting_for_me' => 'people#add_waiting_for_me', :as => :add_waiting_for_me

  match 'people/:id/relations/:id2/add_rejected' => 'people#add_rejected', :as => :add_rejected
  

end

server-test/app/models/person.rb
include ApiHelper

class Person < ActiveRecord::Base
  has_many :to_relations, :class_name => 'PersonRelation', :foreign_key => 'to_id'
  has_many :from_relations, :class_name => 'PersonRelation', :foreign_key => 'from_id'

  after_initialize :default_values

  def offline_since
    return ['Invisible', 'Offline'].include?(self.real_visibility_status) ? self.last_activity_on : nil
  end

  def real_visibility_status
    return (self.last_activity_on.advance(:minutes=>5)).past? ? 'Offline' : self.visibility_status
  end
  
  def friends
    return filter_persons 'Friend'
  end

  def aliens
    return Person.all - self.friends - self.persons_waiting_for_him - self.persons_waiting_for_me - self.rejected_persons - [self]
  end

  def persons_waiting_for_him
    return filter_persons 'WaitingForHim'
  end

  def persons_waiting_for_me
    return filter_persons 'WaitingForMe'
  end

  def last_known_location
    throw "Invalid last known location" unless self.last_known_location_latitude.nil? == self.last_known_location_longitude.nil?
    
    return self.last_known_location_latitude.nil? ? nil : {:latitude => self.last_known_location_latitude, :longitude => self.last_known_location_longitude}
  end

  def last_known_location_to_s
    return self.last_known_location.nil? ? '' : "(#{self.last_known_location_latitude}, #{self.last_known_location_longitude})"
  end

  def rejected_persons
    return filter_persons 'Rejected'
  end

  def looking_for_genders
    result = []
    result << 'Male' if self.looking_for_genders_male
    result << 'Female' if self.looking_for_genders_female
    result << 'Other' if self.looking_for_genders_other

    return result
  end

  def filter_persons friendship_status
    results = []
    self.normalized_relations.each do |r|
        if r[:friendship_status] == friendship_status
          results << r[:person]
        end
    end
    return results
  end

  def find_friendship_status person
    self.normalized_relations.each do |r|
        if r[:person] == person
          return 'Rejected' if r[:rejected_on]
          
          return r[:friendship_status]
        end
    end

    return person == self ? 'Self' : 'Alien'
  end

  def find_rejected_on person
    return person.find_normalized_relation(self).nil? ? nil : person.find_normalized_relation(self)[:rejected_on]
  end

  def calculate_distance lat_1, lng_1, lat_2, lng_2
    r = 6371
    d_lat = (lat_2 - lat_1)/180 * Math::PI
    d_lng = (lng_2 - lng_1)/180 * Math::PI
    lat_1 = lat_1/180 * Math::PI
    lat_2 = lat_2/180 * Math::PI

    a = Math::sin(d_lat/2) * Math::sin(d_lat/2) +
        Math::sin(d_lng/2) * Math::sin(d_lng/2) * Math::cos(lat_1) * Math::cos(lat_2);
    c = 2 * Math::atan2(Math.sqrt(a), Math::sqrt(1-a));
    d = r * c;
    return d.round
  end

  def find_distance_from person
    return 0 if person == self
    return nil if person.last_known_location.nil? || self.last_known_location.nil?
    
    return calculate_distance person.last_known_location_latitude, person.last_known_location_longitude, self.last_known_location_latitude, self.last_known_location_longitude
  end

  def normalized_relations
    results = []
    self.to_relations.each { |r| results << normalize_relation(r) }
    self.from_relations.each { |r| results << normalize_relation(r) }
    
    return results
  end

  def normalize_relation relation
    if relation.relation_status_code == 'Friend'
      return {:person => relation.from, :friendship_status => 'Friend', :rejected_on => relation.rejected_on, :relation => relation} if relation.to == self
      return {:person => relation.to, :friendship_status => 'Friend', :rejected_on => relation.rejected_on, :relation => relation} if relation.from == self
      raise "Invalid relation"
    end

    if relation.relation_status_code == 'WaitingForHim'
      return {:person => relation.from, :friendship_status => 'WaitingForMe', :rejected_on => relation.rejected_on, :relation => relation} if relation.to == self
      return {:person => relation.to, :friendship_status => 'WaitingForHim', :rejected_on => relation.rejected_on, :relation => relation} if relation.from == self
      raise "Invalid relation"
    end

    if relation.relation_status_code == 'Rejected'
      return {:person => relation.from, :friendship_status => 'Rejected', :rejected_on => relation.rejected_on, :relation => relation} if relation.to == self
      return {:person => relation.to, :friendship_status => 'Rejected', :rejected_on => relation.rejected_on, :relation => relation} if relation.from == self
      raise "Invalid relation"
    end
    
    raise "Invalid relation"
  end

  def find_relation person
    return self.find_normalized_relation(person)[:relation]
  end

  def find_normalized_relation person
    return self.normalized_relations.select { |r| r[:person] == person }.first
  end

  def validation_errors
    person = self
    result = []
    
    result << "Invalid email"                   unless !person.email.nil? && !person.email.empty?
    result << "Invalid password"                unless !person.password.nil? && !person.password.empty?
    result << "Invalid visibility status"       unless ['Invisible', 'Online', 'ContactMe'].include?(person.visibility_status)
    result << "Invalid real visibility status"  unless person.real_visibility_status == 'Offline' || person.real_visibility_status == person.visibility_status
    result << "Invalid last activity on"        unless person.last_activity_on.acts_like?(:time)
    result << "Invalid offline since"           unless person.offline_since.nil? || person.offline_since == person.last_activity_on
    result << "Invalid offline since"           unless (!person.offline_since.nil? && (person.real_visibility_status == 'Offline' || person.real_visibility_status == 'Invisible')) ||
                                                    (person.offline_since.nil? && person.real_visibility_status != 'Offline' && person.real_visibility_status != 'Invisible')
    result << "Invalid nick"                    unless !person.nick.nil? && !person.nick.empty?
    result << "Invalid mood"                    unless !person.mood.nil?
    result << "Invalid gravatar code"           unless person.gravatar_code.nil? || !person.gravatar_code.empty?
    result << "Invalid born on"                 unless person.born_on.nil? || person.born_on.acts_like?(:date)
    result << "Invalid gender"                  unless person.gender.nil? || ['Male', 'Female', 'Other'].include?(person.gender)
    result << "Invalid looking for genders"     unless !person.looking_for_genders.nil? && person.looking_for_genders.all? {|g| ['Male', 'Female', 'Other'].include?(g)}
    result << "Invalid phone"                   unless !person.phone.nil?
    result << "Invalid description"             unless !person.description.nil?
    result << "Invalid ocupation"               unless !person.occupation.nil?
    result << "Invalid hobby"                   unless !person.hobby.nil?
    result << "Invalid main location"           unless !person.main_location.nil?
    result << "Invalid last known location"     unless person.last_known_location_latitude.nil? == person.last_known_location_longitude.nil?
    result << "Invalid last known location latitude" unless person.last_known_location_latitude.nil? || person.last_known_location_latitude >= -90 && person.last_known_location_latitude <= 90 && person.last_known_location_latitude == person.last_known_location_latitude.round(4)
    result << "Invalid last known location longitude" unless person.last_known_location_longitude.nil? || person.last_known_location_longitude >= -180 && person.last_known_location_longitude <= 180 && person.last_known_location_longitude == person.last_known_location_longitude.round(4)
    
    return result
  end

  def api_validation_errors current_user
    result = validation_errors
    friendship_status = current_user.find_friendship_status(self)

    result << "Invalid FriendshipStatus" unless ['Self', 'Friend', 'Alien', 'WaitingForHim', 'WaitingForMe', 'Rejected'].include?(current_user.find_friendship_status(self)) &&
                                            (self == current_user && current_user.find_friendship_status(self) == 'Self' ||
                                            self != current_user && current_user.find_friendship_status(self) != 'Self')

    
    rejected_on = current_user.find_rejected_on(self)

    result << "Invalid Rejected_on" unless (!rejected_on.nil? && friendship_status == 'Rejected') ||
                                        (rejected_on.nil? && friendship_status != 'Rejected')

    result << "Invalid distance" unless current_user.find_distance_from(self).nil? || current_user.find_distance_from(self) >= 0
    
    return result
  end

  private
  def default_values
    self.last_activity_on ||= DateTime.now
    self.mood ||= ''
    self.phone ||= ''
    self.description ||= ''
    self.occupation ||= ''
    self.hobby ||= ''
    self.main_location ||= ''
  end
end

server-test/app/controllers/people_controller.rb
#include ApiHelper

class PeopleController < ApplicationController
  # GET /people
  # GET /people.xml
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @people }
    end
  end

  # GET /people/1
  # GET /people/1.xml
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/new
  # GET /people/new.xml
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.xml
  def create
    @person = Person.new(params[:person])
    
    respond_to do |format|
      if @person.save
        @person.gender = nil if @person.gender.empty?
        @person.gravatar_code = nil if @person.gravatar_code.empty?
        @person.save
        format.html { redirect_to(@person, :notice => 'Person was successfully created.') }
        format.xml  { render :xml => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.xml
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        @person.gender = nil if @person.gender.empty?
        @person.gravatar_code = nil if @person.gravatar_code.empty?
        @person.save
        format.html { redirect_to(@person, :notice => 'Person was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.xml
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to(people_url) }
      format.xml  { head :ok }
    end
  end

  def add_friend
    add_relation 'Friend', params[:id], params[:id2], params[:id]
  end

  def add_waiting_for_him
    add_relation 'WaitingForHim', params[:id], params[:id2], params[:id]
  end

  def add_waiting_for_me
    add_relation 'WaitingForHim', params[:id2], params[:id], params[:id]
  end

  def add_rejected
    add_relation 'Rejected', params[:id], params[:id2], params[:id], params[:rejected_on]
  end
  
  def add_relation relation_status, id, id2, id_to_show, rejected_on=nil
    @person_to_show = Person.find(id_to_show)
    @person = Person.find(id)
    @person_relation = PersonRelation.new

    @person_relation.from = @person
    @person_relation.to = Person.find(id2)
    @person_relation.relation_status_code = relation_status
    @person_relation.rejected_on = rejected_on

    respond_to do |format|
      if @person_relation.save
        format.html { redirect_to(@person_to_show, :notice => "#{relation_status} was successfully created.") }
      else
        format.html { redirect_to(@person_to_show, :notice => "#{relation_status} was NOT created.") }
      end
    end
  end
  
  def remove_relation
    @person = Person.find(params[:id])
    @relation = @person.find_relation(Person.find(params[:id2]))

    @relation.destroy

     respond_to do |format|
      format.html { redirect_to(@person) }
      format.xml  { head :ok }
    end
  end
end

server-test/app/helpers/people_helper.rb
module PeopleHelper
end

server-test/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :visibility_status %><br />
    <%= select 'person', 'visibility_status', ['Invisible', 'Offline', 'Online', 'ContactMe'].collect{|status| [status, status]}%>
  </div>
  <div class="field">
    <%= f.label :last_activity_on %><br />
    <%= f.text_field :last_activity_on, :class => 'datetime-picker'%>
  </div>
  <div class="field">
    <%= f.label :nick %><br />
    <%= f.text_field :nick %>
  </div>
  <div class="field">
    <%= f.label :mood %><br />
    <%= f.text_field :mood %>
  </div>
  <div class="field">
    <%= f.label :gravatar_code %><br />
    <%= f.text_field :gravatar_code %>
  </div>
  <div class="field">
    <%= f.label :born_on %><br />
    <%= f.text_field :born_on, :class => 'date-picker'%>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= select 'person', 'gender', ['Male', 'Female', 'Other'].collect{|g| [g, g]}, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :looking_for_genders %><br />
    <%= f.check_box :looking_for_genders_male %> Male
    <%= f.check_box :looking_for_genders_female %> Female
    <%= f.check_box :looking_for_genders_other %> Other
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br />
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :hobby %><br />
    <%= f.text_field :hobby %>
  </div>
  <div class="field">
    <%= f.label :main_location %><br />
    <%= f.text_field :main_location %>
  </div>
  <div class="field">
    <%= f.label :last_known_location %><br />
    Latitude: <%= f.text_field :last_known_location_latitude %> <br />
    Longitude: <%= f.text_field :last_known_location_longitude %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server-test/app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

server-test/app/views/people/friends.html.erb
<h1>Listing friends of <%= @person.nick %></h1>

<table>
  <tr>
    <th>Nick</th>
    <th>Mood</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @person.friends.each do |person| %>
  <tr>
    <td><%= person.nick %></td>
    <td><%= person.mood %></td>
    <td><%= person.email %></td>
    <td><%= person.phone %></td>
    <td><%= person.password %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Back', @person %>

server-test/app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password</th>
    <th>Visibility status</th>
    <th>Real visibility status</th>
    <th>Last Activity on</th>
    <th>Offline since</th>
    <th>Nick</th>
    <th>Mood</th>
    <th>Gravatar code</th>
    <th>Born on</th>
    <th>Gender</th>
    <th>Looking for genders</th>
    <th>Phone</th>
    <th>Description</th>
    <th>Occupation</th>
    <th>Hobby</th>
    <th>Main location</th>
    <th>Last known location</th>
    <th>Validation errors</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.email %></td>
    <td><%= person.password %></td>
    <td><%= person.visibility_status %></td>
    <td><%= person.real_visibility_status %></td>
    <td><%= person.last_activity_on %></td>
    <td><%= person.offline_since %></td>
    <td><%= person.nick %></td>
    <td><%= person.mood %></td>
    <td><%= person.gravatar_code %></td>
    <td><%= person.born_on %></td>
    <td><%= person.gender %></td>
    <td><%= person.looking_for_genders.join(' ') %></td>
    <td><%= person.phone %></td>
    <td><%= person.description %></td>
    <td><%= person.occupation %></td>
    <td><%= person.hobby %></td>
    <td><%= person.main_location %></td>
    <td><%= person.last_known_location_to_s %></td>
    <td><%= person.validation_errors %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

server-test/app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

server-test/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @person.email %>
</p>

<p>
  <b>Password:</b>
  <%= @person.password %>
</p>

<p>
  <b>Visibility status:</b>
  <%= @person.visibility_status %>
</p>

<p>
  <b>Real visibility status:</b>
  <%= @person.real_visibility_status %>
</p>

<p>
  <b>Last activity on:</b>
  <%= @person.last_activity_on %>
</p>

<p>
  <b>Offline since:</b>
  <%= @person.offline_since %>
</p>

<p>
  <b>Nick:</b>
  <%= @person.nick %>
</p>

<p>
  <b>Mood:</b>
  <%= @person.mood %>
</p>

<p>
  <b>Gravatar code:</b>
  <%= @person.gravatar_code %>
</p>

<p>
  <b>Born on:</b>
  <%= @person.born_on %>
</p>

<p>
  <b>Gender:</b>
  <%= @person.gender%>
</p>

<p>
  <b>Looking for genders:</b>
  <%= @person.looking_for_genders.join(' ') %>
</p>

<p>
  <b>Phone:</b>
  <%= @person.phone %>
</p>

<p>
  <b>Description:</b>
  <%= @person.description %>
</p>

<p>
  <b>Occupation:</b>
  <%= @person.occupation %>
</p>

<p>
  <b>Hobby:</b>
  <%= @person.hobby %>
</p>

<p>
  <b>Main location:</b>
  <%= @person.main_location %>
</p>

<p>
  <b>Last known location:</b>
  <%= @person.last_known_location_to_s %>
</p>

<p>
  <b>Validation errors:</b>
  <%= @person.validation_errors %>
</p>

<table>
  <tr>
    <td>
      <b>Friends:</b>
      <ul>
        <% @person.friends.each do |person| %>
          <li>
            <%= person.nick + (person.find_distance_from(@person).nil? ? '' : " [#{person.find_distance_from(@person)} m]") %>
            <%= link_to 'Show', person %>
            <%= link_to 'Remove', remove_relation_path(@person, person)%>
          </li>
        <% end %>
      </ul>
      <select onchange="location = this.options[this.selectedIndex].value;">
        <option>Add...</option>
        <% @person.aliens.each do |person| %>
          <option value="<%= add_friend_path(@person, person) %>"><%= person.nick %></option>
        <% end %>
      </select>
    </td>
    <td>
      <b>Aliens:</b>
      <ul>
        <% @person.aliens.each do |person| %>
          <li>
            <%= person.nick + (person.find_distance_from(@person).nil? ? '' : " [#{person.find_distance_from(@person)} m]") %>
            <%= link_to 'Show', person %>
          </li>
        <% end %>
      </ul>
    </td>
    <td>
      <b>Waiting for me:</b>
      <ul>
        <% @person.persons_waiting_for_me.each do |person| %>
          <li>
            <%= person.nick + (person.find_distance_from(@person).nil? ? '' : " [#{person.find_distance_from(@person)} m]") %>
            <%= link_to 'Show', person %>
            <%= link_to 'Remove', remove_relation_path(@person, person) %>
          </li>
        <% end %>
      </ul>
      <select onchange="location = this.options[this.selectedIndex].value;">
        <option>Add...</option>
        <% @person.aliens.each do |person| %>
          <option value="<%= add_waiting_for_me_path(@person, person) %>"><%= person.nick %></option>
        <% end %>
      </select>
    </td>
    <td>
      <b>Waiting for him:</b>
      <ul>
        <% @person.persons_waiting_for_him.each do |person| %>
          <li>
            <%= person.nick + (person.find_distance_from(@person).nil? ? '' : " [#{person.find_distance_from(@person)} m]") %>
            <%= link_to 'Show', person %>
            <%= link_to 'Remove', remove_relation_path(@person, person)%>
          </li>
        <% end %>
      </ul>
      <select onchange="location = this.options[this.selectedIndex].value;">
        <option>Add...</option>
        <% @person.aliens.each do |person| %>
          <option value="<%= add_waiting_for_him_path(@person, person) %>"><%= person.nick %></option>
        <% end %>
      </select>
    </td>
    <td>
      <b>Rejected:</b>
      <ul>
        <% @person.rejected_persons.each do |person| %>
          <li>
            <%= person.nick + (person.find_distance_from(@person).nil? ? '' : " [#{person.find_distance_from(@person)} m]") %>
            <%= @person.find_rejected_on(person) %>
            <%= link_to 'Show', person %>
            <%= link_to 'Remove', remove_relation_path(@person, person) %>
          </li>
        <% end %>
      </ul>
      <select onchange="location = this.options[this.selectedIndex].value + '?rejected_on=' + (jQuery('rejected-on-textbox').value != undefined ? jQuery('rejected-on-textbox').value : dateFormat('isoDateTime'));">
        <option>Add...</option>
        <% @person.aliens.each do |person| %>
          <option value="<%= add_rejected_path(@person, person) %>"><%= person.nick %></option>
        <% end %>
      </select>
      <input id="rejected-on-textbox" class="datetime-picker"></input>
    </td>
  </tr>
</table>
<p>
  
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %> |