server-test/config/routes.rb
SnaTest::Application.routes.draw do
  resources :messages

  resources :person_relations

  resources :people

  match 'api/data/' => 'api#get_data', :via => :get

  match 'api/profile/' => 'api#register_profile', :via => :post
  
  match 'api/profile/' => 'api#update_profile', :via => :get

  match 'api/persons/*person_email/request-friendship/' => 'api#request_friendship', :via => :post

  match 'api/persons/*person_email/reject-friendship/' => 'api#reject_friendship', :via => :post

  match 'api/messages/*person_email/send-message/' => 'api#send_message', :via => :post

  match 'api/messages/:message_id/mark-as-read/' => 'api#mark_message_read', :via => :put

  match 'people/:id/friends' => 'people#friends', :as => :person_friends

  match 'people/:id/relations/:id2/remove' => 'people#remove_relation', :as => :remove_relation

  match 'people/:id/relations/:id2/add_friend' => 'people#add_friend', :as => :add_friend

  match 'people/:id/relations/:id2/add_waiting_for_him' => 'people#add_waiting_for_him', :as => :add_waiting_for_him

  match 'people/:id/relations/:id2/add_waiting_for_me' => 'people#add_waiting_for_me', :as => :add_waiting_for_me

  match 'people/:id/relations/:id2/add_rejected' => 'people#add_rejected', :as => :add_rejected
  

end

server-test/app/models/person_relation.rb
class PersonRelation < ActiveRecord::Base
  belongs_to :from, :class_name => 'Person'
  belongs_to :to, :class_name => 'Person'
end

server-test/app/controllers/person_relations_controller.rb
class PersonRelationsController < ApplicationController
  # GET /person_relations
  # GET /person_relations.xml
  def index
    @person_relations = PersonRelation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @person_relations }
    end
  end

  # GET /person_relations/1
  # GET /person_relations/1.xml
  def show
    @person_relation = PersonRelation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @person_relation }
    end
  end

  # GET /person_relations/new
  # GET /person_relations/new.xml
  def new
    @person_relation = PersonRelation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @person_relation }
    end
  end

  # GET /person_relations/1/edit
  def edit
    @person_relation = PersonRelation.find(params[:id])
  end

  # POST /person_relations
  # POST /person_relations.xml
  def create
    @person_relation = PersonRelation.new(params[:person_relation])

    respond_to do |format|
      if @person_relation.save
        format.html { redirect_to(@person_relation, :notice => 'Person relation was successfully created.') }
        format.xml  { render :xml => @person_relation, :status => :created, :location => @person_relation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @person_relation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /person_relations/1
  # PUT /person_relations/1.xml
  def update
    @person_relation = PersonRelation.find(params[:id])

    respond_to do |format|
      if @person_relation.update_attributes(params[:person_relation])
        format.html { redirect_to(@person_relation, :notice => 'Person relation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @person_relation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /person_relations/1
  # DELETE /person_relations/1.xml
  def destroy
    @person_relation = PersonRelation.find(params[:id])
    @person_relation.destroy

    respond_to do |format|
      format.html { redirect_to(person_relations_url) }
      format.xml  { head :ok }
    end
  end
end

server-test/app/helpers/person_relations_helper.rb
module PersonRelationsHelper
end

server-test/app/views/person_relations/_form.html.erb
<%= form_for(@person_relation) do |f| %>
  <% if @person_relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person_relation.errors.count, "error") %> prohibited this person_relation from being saved:</h2>

      <ul>
      <% @person_relation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :from_id %><br />
    <%= select 'person_relation', 'from_id', Person.all.collect{|p| [p.email, p.id]}%>
  </div>
  <div class="field">
    <%= f.label :to_id %><br />
    <%= select 'person_relation', 'to_id', Person.all.collect{|p| [p.email, p.id]}%>
  </div>

  <div class="field">
    <%= f.label :relation_status_code %><br />
    <%= select 'person_relation', 'relation_status_code', ['Friend', 'WaitingForHim', 'Rejected'].collect{|status| [status, status]}%>
  </div>

  <div class="field">
    <%= f.label :rejected_on %><br />
    <%= f.text_field :rejected_on, :class => 'datetime-picker'%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server-test/app/views/person_relations/edit.html.erb
<h1>Editing person_relation</h1>

<%= render 'form' %>

<%= link_to 'Show', @person_relation %> |
<%= link_to 'Back', person_relations_path %>

server-test/app/views/person_relations/index.html.erb
<h1>Listing person_relations</h1>

<table>
  <tr>
    <th>From</th>
    <th>To</th>
    <th>Relation status code</th>
    <th>Rejected on</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @person_relations.each do |person_relation| %>
  <tr>
    <td><%= person_relation.from.email %></td>
    <td><%= person_relation.to.email %></td>
    <td><%= person_relation.relation_status_code %></td>
    <td><%= person_relation.rejected_on %></td>
    <td><%= link_to 'Show', person_relation %></td>
    <td><%= link_to 'Edit', edit_person_relation_path(person_relation) %></td>
    <td><%= link_to 'Destroy', person_relation, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person relation', new_person_relation_path %>

server-test/app/views/person_relations/new.html.erb
<h1>New person_relation</h1>

<%= render 'form' %>

<%= link_to 'Back', person_relations_path %>

server-test/app/views/person_relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>From:</b>
  <%= @person_relation.from.email %>
</p>

<p>
  <b>To:</b>
  <%= @person_relation.to.email %>
</p>

<p>
  <b>Relation status code:</b>
  <%= @person_relation.relation_status_code %>
</p>

<p>
  <b>Rejected on:</b>
  <%= @person_relation.rejected_on %>
</p>


<%= link_to 'Edit', edit_person_relation_path(@person_relation) %> |
<%= link_to 'Back', person_relations_path %>